### ISSUE TITLE
Vendor directory not in .gitignore

### ISSUE THREAD

**Issue by Dimidel** [bitfumes/phonebook#1]
All is in the title : )

**Comment by goranGG** [comment]
if you watch [youtube series](https://www.youtube.com/watch?v=pBB_zVNIoTI&list=PLe30vg_FG4OSl8zlikYc_RLkfueqAMUb_&index=3)
he said he will upload everything for new people (only node modules will be excluded due its size)

**Comment by Dimidel** [comment]
Thank you @night5talker. I didn't notice that !
