### ISSUE TITLE
Search and delete not working properly

### ISSUE THREAD

**Issue by shofin-islam** [bitfumes/phonebook#4]
Its delete from list, not from temp.

Can you help?

**Comment by alhavizd** [comment]
you can see "Pull requests"
hopefully it answers your question

**Comment by shofin-islam** [comment]
i have solved by another way,
indexWhere(array, conditionFn) {
				const item = array.find(conditionFn)
				return array.indexOf(item)
			}
if (this.$data.searchQuery != '') {
							const assetindex = this.indexWhere(this.Assets, item => item.id === id);

							if(tempindex >-1)
							{
								this.temp.splice(tempindex,1);
							}
							if (assetindex >-1) {
								this.Assets.splice(assetindex,1);
							}
						}else{
							this.Assets.splice(key,1)
						}
